### ISSUE TITLE
tests occasionally fail with 'reason: :closed'

### ISSUE THREAD

**Issue by mkrogemann** [locolupo/couchdb_connector#2]
stacktrace of a failed test

  1) test create/3: ensure that wrong database properties results in an error on write (Couchdb.Connector.WriterTest)
     test/couchdb_connector/writer_test.exs:20
     ** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :closed}}
     stacktrace:
       test/test_prep.exs:11: Couchdb.Connector.TestPrep.delete_database/0
       (ex_unit) lib/ex_unit/on_exit_handler.ex:82: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit) lib/ex_unit/on_exit_handler.ex:66: ExUnit.OnExitHandler.on_exit_runner_loop/0

**Comment by locolupo** [comment]
with #8 we are avoiding travis-ci docker builds, this could solve our issues
