### ISSUE TITLE
key parameters for view queries are not UrlEscaped

### ISSUE THREAD

**Issue by tomjoro** [locolupo/couchdb_connector#24]
I have a view which has sorted phone numbers, keys with "+" don't work. Should the connector provide URLescaping of parameters by default?

This doesn't work: It returns 0 results.

{:ok, result} = Couchdb.Connector.View.document_by_key(db, "test_queries", "by_phone_number", "+358123456789")

GET /test_users/_design/test_queries/_view/by_phone_number?key="+358123456789"&stale=update_after 200

This works:

{:ok, result} = Couchdb.Connector.View.document_by_key(db, "test_queries", "by_phone_number", "%2B358123456789")

GET /test_users/_design/test_queries/_view/by_phone_number?key="%2B358123456789"&stale=update_after 200

**Comment by mkrogemann** [comment]
Thanks for reporting this.
I will add Percent-encoding for the query path in v0.4.1
ETA: Tomorrow

**Comment by mkrogemann** [comment]
Fixed in dev

**Comment by mkrogemann** [comment]
Fixed in 0.4.1
