### ISSUE TITLE
Add Basic Auth for database creation

### ISSUE THREAD

**Issue by leifg** [locolupo/couchdb_connector#32]
I noticed there is no way to create a database with basic authentication.

This is necessary when you can't access you database on localhost (docker is a typical example).

Would you merge a PR if I provided one?

**Comment by mkrogemann** [comment]
I am more than happy to look at your PR. 
I think that I do create databases in the integration tests that are protected with basic auth.
The API may not be exposed/documented properly though, so a good time to look at this and at your requirements.

**Comment by leifg** [comment]
OK I will look into providing a pull request soon.

I haven't found any part where there is a database created with basic_auth. I have however found this: https://github.com/locolupo/couchdb_connector/blob/master/test/test_prep.exs where the calls are made directly via HTTP.

**Comment by mkrogemann** [comment]
You are quite right. It's currently missing in the API. Thanks for bringing this up!

**Comment by mkrogemann** [comment]
Fixed in PR #35
