### ISSUE TITLE
Accept maps in writing API

### ISSUE THREAD

**Issue by leifg** [locolupo/couchdb_connector#33]
I noticed that it's only possible to pass json strings to the writer.

I also see that the json is [parsed into a map](https://github.com/locolupo/couchdb_connector/blob/master/lib/couchdb_connector/writer.ex#L111) for some sanitation.

I think it makes sense to allow maps to be passed into the create method to save back and forth parsing.

**Comment by mkrogemann** [comment]
Which release are you looking at? I have added a bunch of functions lately that accept and return Maps. It is not unlikely that there are still gaps. Please point me to the exact case.
Thanks!

**Comment by leifg** [comment]
It's `create` and `create_generate` in the Writer module:

https://github.com/locolupo/couchdb_connector/blob/master/lib/couchdb_connector/writer.ex#L41
https://github.com/locolupo/couchdb_connector/blob/master/lib/couchdb_connector/writer.ex#L84

**Comment by mkrogemann** [comment]
Ah, I see. I have added the Map-consuming functions "one level higher", in the module Couchdb.Connector. I guess I could make that clearer in the documentation. 
Anyhow, in there, you should find `create` and `create_generate` functions that consume Maps.
Is this what you are after?

**Comment by leifg** [comment]
Ah I see, [this](https://github.com/locolupo/couchdb_connector/blob/master/lib/couchdb_connector.ex#L118) is what I was looking for.

The only problem that remains is the back and forth encoding and decoding but it's a minor one (input map, encode to json, decode to map to remove id key, encode to json again).

**Comment by mkrogemann** [comment]
Yes, you are right. There is room for improvement. I'll create a task/issue to look into that.
