### ISSUE TITLE
Deprecation Strategy

### ISSUE THREAD

**Issue by leifg** [locolupo/couchdb_connector#39]
After #38 there is a lot of deprecated code.

I personally would like to remove all deprecated functions. I don't know what the general opinion is.

I understand the backwards compatibility will break, but ultimately it will make the code a lot cleaner.

**Comment by mkrogemann** [comment]
I agree that the deprecated code should be removed.
But I intend to do this with a new version. One that signals the backward incompatible nature of the changes.
My latest plan had been to have a 0.5 release soon where all deprecated code would be removed. I don't see much value in doing a 0.4.4 release with the latest improvements now, we might as well go ahead and bump to 0.5. What's your view?

**Comment by mkrogemann** [comment]
On second thought: I guess it would be fair to release the current state (including your auth improvements) as a 0.4.4 and then remove all the deprecated stuff and do a 0.5.0

**Comment by leifg** [comment]
sounds like a good solution. when there is a new release I remove the deprecated methods

**Comment by mkrogemann** [comment]
Ok, this is how I will proceed then:
- Add to the change log
- Write a few more words on authentication in the README
- Do the release
- Comment and close this ticket
- Remove the things that I had already deprecated in earlier releases
- hand over to you :)

**Comment by leifg** [comment]
Sounds good. Looking forward to it.

**Comment by mkrogemann** [comment]
All deprecated functions are gone, also some more functions that were not yet deprecated but should have been.
Test coverage is back to 100%.
Please feel free to do a review.

**Comment by mkrogemann** [comment]
I think this can be closed now
