### ISSUE TITLE
Handle attachments.

### ISSUE THREAD

**Issue by uDude** [locolupo/couchdb_connector#41]
I have code ready for the dev branch (soon) that handles attachments.  I am meticulously  going through tests and fixing bugs.

**Comment by mkrogemann** [comment]
Hey @uDude, how is the attachment handling coming along? Can I support you in any way, such as review code, help fix a bug, etc?

**Comment by uDude** [comment]
I'll sync my local dev to my fork (dev branch) on github tonight.  I'm
writing test code for the function additions in reader and writer.

UDude

**Comment by uDude** [comment]
I synced to my dev branch where I am.  All functions written.  Not all
tests are written (see test/NOTES).  Comments with MFK or TODO are spots to
come back to in the code.

One private function needs to be rewritten (fetches the filename from a
string -- it is unix spicific, my bad.  I use *nix exclusively so I forget
to be windows generic sometimes).

Mike

**Comment by uDude** [comment]
I see the problem. I should be able to fix it this weekend.  In resolving conflicts I accidentally deleted Url_Helper.database_url().
