### ISSUE TITLE
Couchdb.Connector.Writer.create/2 undefined

### ISSUE THREAD

**Issue by didiercauvin** [locolupo/couchdb_connector#43]
Hi there,

it seems that I can't do Couchdb.Connector.Writer.create(db_props, "{\"key\": \"value\"}") as Couchdb.Connector.Writer.create/2 is undefined. Only Couchdb.Connector.Writer.create/3 is available. What if I don't want to pass an id?

Thanks for your reply,
Didier

**Comment by locolupo** [comment]
Hi

you can use ```create_generate``` in this case 

https://hexdocs.pm/couchdb_connector/Couchdb.Connector.Writer.html#create_generate/2

>  Create a new document with given json and a CouchDB generated id.
  Fetching the uuid from CouchDB does of course incur a performance penalty as
  compared to providing one.

**Comment by didiercauvin** [comment]
Hi,

thanks for your reply, I totally missed it...

**Comment by locolupo** [comment]
> thanks for your reply, I totally missed it..

no problem, glad to help
