### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by majkilde** [locolupo/couchdb_connector#9]
When running 'mix deps.get' I get this error:

Running dependency resolution
Conflict on poison 2.1.0
  mix.lock: 2.1.0
  couchdb_connector 0.2.0: ~> 1.5.0
  phoenix 1.1.4: ~> 1.5 or ~> 2.0

** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

How do I solve this?

**Comment by mkrogemann** [comment]
I have not yet been able to reproduce this. 
I updated phoenix to 1.1.4 but the dependencies still resolve. How does the dependency to poison 2.1.0 get into the project?
I may try to make the connector work with this more recent version but would like to first understand, why the dependency differs from my case.
I paste here the relevant settings of my mix.exs and attach the mix.lock file.

  defp deps do
    [
      {:phoenix, "~> 1.1"},
      {:phoenix_html, "~> 2.3"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:cowboy, "~> 1.0"},
      {:httpoison, "~> 0.8.0"},
      {:coverex, "~> 1.4.7", only: [:dev, :test]},
      {:poison, "~> 1.5"},
      {:couchdb_connector, "~> 0.2"},
      {:credo, "~> 0.2", only: [:dev, :test]}
    ]
  end

[mix.lock.txt](https://github.com/locolupo/couchdb_connector/files/198355/mix.lock.txt)

**Comment by locolupo** [comment]
> I have not yet been able to reproduce this. 

same here.

@majkilde is your hex version uptodate? pls try to update via ``` mix local.hex```

if this does not help please remove your hex.lock file and perform ```mix deps.get``` again

**Comment by mkrogemann** [comment]
Just noticed that we have 2.1.0 as a dependency in the connector. Will investigate further

**Comment by mkrogemann** [comment]
ok, it looks like we can simply downgrade. this should solve your issue @majkilde, right?

**Comment by majkilde** [comment]
Yes, that should work.
I found a workaround. It worked when I used github directly instead of hex.

This works:
{:couchdb_connector, git: "https://github.com/locolupo/couchdb_connector", tag: "master"}, 

But this didn't: #{:couchdb_connector, "~> 0.2.0"},

It seams like the Hex has a Poison 1.5.0 (shows on this page: https://hex.pm/packages/couchdb_connector), but Github has Poison 2.1.0 (https://github.com/locolupo/couchdb_connector/blob/master/mix.exs)

**Comment by mkrogemann** [comment]
The upcoming 0.4.0 release will allow for a wider range of poison versions. We will adopt the same range that Phoenix is using:
{:poison, "~> 1.5 or ~> 2.0"}
This should allow you to switch back to the released version.
